Repository twilio-labs/open-pixel-art, pull requests merged in 2019-11, with the labels that each got.

#916 docs(contributing): add section on syncing fork
  CONTRIBUTING.md
Labels: hacktoberfest, needs-help

#1611 docs(de): update contributing file
  docs/de/CONTRIBUTING.md
Labels: hacktoberfest, needs-help

#1507 (feat): Add Gravity
  assets/javascript/party-mode.js
  index.njk
Labels: hacktoberfest, needs-help, needs-review

#1724 refactor: use display:none to reduce DOM mutations
  assets/javascript/party-mode.js
Labels: hacktoberfest, needs-help

#1729 add pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#1764 feat(pixels): add my new pixel (22, 19)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1778 docs: add dutch translation for CONTRIBUTING.md
  README.md
  docs/nl/CONTRIBUTING.md
Labels: hacktoberfest, needs-help, needs-review

#1775 feat(pixels): add my new pixel(26,31)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1259 feat(pixels): add new pixel (38, 31)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1708 New pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1704 Added pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#1774 Pixel added at y:16 x:15
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review, pixel-contribution

#1804 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#1812 add my pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1824 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#1842 feat(pixels): adds my pink pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1851 My branch name
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution
