Repository twilio-labs/open-pixel-art, pull requests merged in 2019-10, with the labels that each got.

#19 feat: update website with new header
  assets/open-pixel-art-logo.svg
  assets/twilioBug.svg
  index.njk
  styles/main.css
Labels: needs-review

#20 feat: add meta tags to website
  assets/open-graph-image.png
  assets/open-graph-image.svg
  index.njk
Labels: needs-review

#21 Update pixels.json
  _data/pixels.json
Labels: hacktoberfest, needs-help

#22 fix: Danger should not throw an error for an empty PR (#15)
  dangerfile.js
Labels: hacktoberfest, needs-help

#32 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#34 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#33 Claim pixel and change color
  _data/pixels.json
Labels: hacktoberfest, needs-help

#36 Add new row in pixels.json
  _data/pixels.json
Labels: hacktoberfest, needs-help

#42 Modify
  _data/pixels.json
Labels: hacktoberfest, needs-help

#43 Super
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#46 fix: improve danger diff checking
  dangerfile.js
Labels: hacktoberfest, needs-help

#47 abdulajet: add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#48 Hello ines
  _data/pixels.json
Labels: hacktoberfest, needs-help

#51 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#53 test: add check no username is commited with angle bracke…
  __tests__/data.test.js
  _data/pixels.json
  package-lock.json
Labels: hacktoberfest, needs-help, needs-review

#54 fix: match usernames case independent
  dangerfile.js
Labels: hacktoberfest, needs-help

#55 feat(pixels): add lex111's pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#60 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#61 feat(pixels): add mtheoryx pixels
  _data/pixels.json
Labels: hacktoberfest, needs-help

#68 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#66 feat(pixels): add my new pixel (simeydk)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#69 feat(pixels): add by rightturn
  _data/pixels.json
Labels: hacktoberfest, needs-help

#74 feat(pixels): Add new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#67 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#70 feat: added pixel contributor indicator
  assets/javascript/name-hover.js
  index.njk
Labels: hacktoberfest, needs-help, needs-review

#82 Dev
  _data/pixels.json
Labels: hacktoberfest, needs-help

#98 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#99 feat(pixels): add new pink pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#40 Twilio
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#130 Added a new Pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#135 #127 - Create new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#129 Hacktober
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#156 Steves pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#150 add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#174 add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#190 add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#189 Adding my pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#191 add coordinates for adilhussain
  _data/pixels.json
Labels: hacktoberfest, needs-help

#196 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#212 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#213 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#147 feat(pixel): add #33ffca y 12 x 7 as lillialskye
  _data/pixels.json
  assets/javascript/name-hover.js
  package-lock.json
Labels: hacktoberfest, needs-help, needs-review

#194 added IDE & editors specific files in .gitignore
  .gitignore
Labels: hacktoberfest, needs-help

#178 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#230 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#177 chore(docs): translate contributing.md to spanish
  CONTRIBUTING.md
  README.md
  docs/es/CONTRIBUTING.md
Labels: hacktoberfest, needs-help, needs-review

#237 Sort task
  package-lock.json
  package.json
  tasks/sortPixels.js
Labels: needs-review

#219 Added pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#158 Melissa/pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#242 docs(contributing) translate to spanish note about order of entries
  CONTRIBUTING.md
  docs/es/CONTRIBUTING.md
Labels: hacktoberfest, needs-help, needs-review

#249 add my pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#251 feat(pixels): add new pixel at y:35 x:5
  _data/pixels.json
Labels: hacktoberfest, needs-help

#252 Added orange pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#254 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#253 Add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#255 adding a pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#257 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#246 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#258 added new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#141 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#261 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#262 added pixel -somaditya
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#269 Shadowborn at 19 21
  _data/pixels.json
Labels: hacktoberfest, needs-help

#267 Add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#264 Add ma new Pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#270 Add new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#272 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#273 Added new zima blue pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#275 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#279 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#289 feat(pixels): add a new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#294 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#298 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#301 Fix my hex
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#303 Update pixels.json
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#305 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#306 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#308 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#322 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#321 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#222 test: add unique position test
  __tests__/data.test.js
Labels: hacktoberfest, needs-help, needs-review

#299 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#302 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#313 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#316 feat(pixels): oshka has added her new violet pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#323 Made a pretty blue pixel, this is super cute!
  _data/pixels.json
Labels: hacktoberfest, needs-help

#284 feat: improve hover pixel abilty(#226) and color contrast (#217)
  _data/pixels.json
  assets/javascript/name-hover.js
  index.njk
  styles/main.css
Labels: hacktoberfest, needs-help, needs-review

#326 Added pixel and fixed formatting
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#285 Claim pixel and change color
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#335 feat(pixels):add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#334 My pixel Art.
  _data/pixels.json
Labels: hacktoberfest, needs-help

#346 docs(readme-code-of-conduct): fix typos
  docs/es/CODE_OF_CONDUCT.md
Labels: hacktoberfest, needs-help

#352 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest, needs-help

#353 Added my pixel :)
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#356 feat(pixels): add my new pixel - @tigerrobocop
  _data/pixels.json
Labels: hacktoberfest, needs-help

#357 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#365 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#364 Update contributing guidelines
  CONTRIBUTING.md
Labels: hacktoberfest, needs-help

#345 feat: add Screen Reader Accessibility improvements
  index.njk
  styles/main.css
Labels: hacktoberfest, needs-help, needs-review

#369 style: sort pixels
  __tests__/data.test.js
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#348 test: improve duplicate test
  __tests__/data.test.js
Labels: hacktoberfest, needs-help

#359 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#363 Added @iamthismarvin pixel.
  _data/pixels.json
Labels: hacktoberfest, needs-help

#373 Add a pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#376 feat(pixels): add my new pixel (19, 21)
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#379 feat(pixels): add my new pixel (20, 12)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#388 Add my pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#405 feat(pixels): add my new pixel (0, 3) (:
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#430 feat(pixels): add my new pixel (x38 27)
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#427 feat(pixels): add my new pixel (36, 36)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#439 Added a new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#397 feat(pixels): add my new pixel (25, 13)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#451 feat(pixels): add my new pixel (29, 12)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#483 feat(pixels): add my new pixel (10, 9)
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#408 feat(pixels): add my new pixel (29, 30)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#400 added retro-node pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#407 feat(pixels): add my new pixel (1, 28)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#386 feat(pixels): add my new pixel (9, 39)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#382 Adding my colour
  _data/pixels.json
Labels: hacktoberfest, needs-help

#385 feat(pixels): add my new pixel (39, 27)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#378 feat: Claimed my new pixel (x, y)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#402 feat(pixels): add my new pixel (12, 12)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#435 feat(pixels): add my new pixel (7, 30)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#396 feat(pixels): add my new pixel (28, 28)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#428 New pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#416 feat(pixels): add my new pixel (36, 29)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#426 Darp new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#415 Pixel Done and Test
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#490 Add pixel
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#421 feat(pixels): add my new pixel (35, 39)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#404 fix: Minor fixes
  __tests__/data.test.js
  _data/pixels.json
  styles/main.css
Labels: hacktoberfest, needs-help, needs-review

#467 fix: add missing attributes to TQ download link #466
  index.njk
Labels: hacktoberfest, needs-help, needs-review

#474 fix: remove horizontal scroll
  styles/main.css
Labels: hacktoberfest, needs-help

#494 Update pixels.json
  _data/pixels.json
Labels: hacktoberfest, needs-help

#493 Added my pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#437 added new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#459 feat(pixels): add my new pixel (29, 22)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#461 feat(pixels): add my new pixel (23, 24)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#469 Added My Pixel With One Of My ♥️ Colour
  _data/pixels.json
Labels: hacktoberfest, needs-help

#470 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#465 pixel (35,4) dayramaelbranz
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review, pixel-contribution

#476 feat(pixels): add my new pixel (39, 21)
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#482 feat(pixels): add my new pixel (23, 18)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#486 feat(pixels): add my new pixel (19, 39)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#485 feat(pixels) : add my new pixel (6, 39)
  _data/pixels.json
Labels: hacktoberfest, pixel-contribution

#491 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#496 feat(pixels): add my new pixel (7, 2)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#500 feat(pixels): add my new pixel (5, 38)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#502 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#498 feat(pixels): add my new pixel (28, 20)
  _data/pixels.json
Labels: hacktoberfest, needs-help
