Repository twilio-labs/open-pixel-art, pull requests merged in 2020-10, with the labels that each got.

#2618 feat (pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2622 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2662 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2650 New pixel
  _data/pixels.json
Labels: needs-help

#2626 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2694 feat(pixels): add my new pixel (8, 17)
  _data/pixels.json
Labels: pixel-contribution

#2705 Update pixels.json
  _data/pixels.json
Labels: needs-help

#2718 feat(pixels): add my new pixel (30, 50)
  _data/pixels.json
Labels: needs-help

#2721 feat(pixels): add my new pixel (58, 0)
  _data/pixels.json
Labels: needs-help

#2743 feat(pixels):add my new pixel (26,26)
  _data/pixels.json
Labels: needs-help

#2744 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2746 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2751 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2671 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2760 feat(pixels): add my new pixel (28,59)
  _data/pixels.json
Labels: needs-help

#2763 feat(pixels): add my new pixel (48, 31)
  _data/pixels.json
Labels: needs-help

#2762 feat(pixels): add my new pixel (7, 3)
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2778 added my pixel
  _data/pixels.json
Labels: pixel-contribution

#2779 feat(pixels): add my new pixel (31, 50)
  _data/pixels.json
Labels: needs-help

#2791 feat(pixels): add my new pixel (38,20)
  _data/pixels.json
Labels: needs-help

#2795 feat: Add my pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2796 feat: Add my pixel
  _data/pixels.json
Labels: needs-help

#2800 Add mypixel
  _data/pixels.json
Labels: needs-help

#2802 feat: add my pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2809 feat(pixels): add my new pixel (48, 32)
  _data/pixels.json
Labels: needs-help

#2811 feat(pixels): add my new pixel (50, 32)
  _data/pixels.json
Labels: needs-help

#2817 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2818 a
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2674 feat(pixels): add my new pixel(45, 45)
  _data/pixels.json
Labels: needs-help

#2866 Added new pixel
  _data/pixels.json
Labels: needs-help

#2868 feat(pixels): add my new pixel (60, 0)
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2930 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help
