Repository twilio-labs/open-pixel-art, pull requests merged in 2020-09, with the labels that each got.

#2427 feat(pixels): Adding my pixel
  _data/pixels.json
Labels: needs-help

#2533 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2545 feat(pixels): add my new pixel (41, 39)
  _data/pixels.json
Labels: needs-help

#2548 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2561 elijah-atkins
  _data/pixels.json
Labels: needs-help, needs-review

#2566 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#2600 Newbranch
  _data/pixels.json
Labels: needs-help, needs-review

#2601 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2568 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#2609 removed pixel
  _data/pixels.json
Labels: needs-help
