Repository twilio-labs/open-pixel-art, pull requests merged in 2020-02, with the labels that each got.

#1939 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1940 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1941 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1927 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1944 gessnern was here
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1946 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1943 feat: add pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#1953 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1959 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1965 feat(pixels): add my new pixel (43, 7)
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1961 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1962 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1967 Update pixels
  _data/pixels.json
Labels: hacktoberfest, needs-help, pixel-contribution

#1964 Tarmo branch
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1969 add pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1968 Cheesecake
  _data/pixels.json
Labels: hacktoberfest, needs-help, needs-review

#1970 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help

#1974 feat(pixels): add my new pixel
  _data/pixels.json
Labels: hacktoberfest, needs-help
