Repository twilio-labs/open-pixel-art, pull requests merged in 2021-02, with the labels that each got.

#3468 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3059 feat(pixels): Add my shiny new pixel (torquoise)
  _data/pixels.json
Labels: needs-help

#3481 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#3493 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3494 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3497 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#3507 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3510 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help, pixel-contribution

#3531 Add pixel
  _data/pixels.json
Labels: needs-help

#3539 Added my pixel :D Emilio0404
  _data/pixels.json
Labels: pixel-contribution

#3542 Pixel de Alejandro
  _data/pixels.json
Labels: pixel-contribution

#3541 Pixel de Jorge
  _data/pixels.json
Labels: pixel-contribution

#3540 Pixel of Armando from mexico
  _data/pixels.json
Labels: pixel-contribution

#3202 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3558 Updated pixels.json
  _data/pixels.json
Labels: needs-help

#3567 feat(pixels): add my new pixel
  _data/pixels.json
Labels: needs-help

#3570 Merge pull request #1 from twilio-labs/master
  _data/pixels.json
Labels: needs-help
